name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-ecommerce:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-ecommerce:${IMAGE_TAG}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Set up Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Print kubeconfig (Debugging)
        run: cat $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Get Kubernetes Contexts (Debugging)
        run: kubectl config get-contexts
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl set image deployment/api-ecommerce-deployment api-ecommerce=${{ secrets.DOCKER_USERNAME }}/api-ecommerce:${{ env.IMAGE_TAG }}
        env:
          KUBECONFIG: $HOME/.kube/config
