on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_PRODUCTION_USERNAME }}
          server: ${{ secrets.FTP_PRODUCTION_SERVER }}
          password: "${{ secrets.FTP_PRODUCTION_PASSWORD}}"
          sftp_only: true
          remote_path: './uploads/'
          local_path: "./*"